apiVersion: v1
kind: Service
metadata:
  name: dev-game-server
  namespace: 5stack
spec:
  selector:
    app: dev-game-server
  ports:
    - name: game-tcp
      port: 27015
      protocol: TCP
    - name: game-udp
      port: 27015
      protocol: UDP
    - name: tv-tcp
      port: 27020
      protocol: TCP
    - name: tv-udp
      port: 27020
      protocol: UDP

