apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: relay
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /match-relay/$1
  namespace: 5stack
spec:
  ingressClassName: nginx
  rules:
    - host: $(RELAY_DOMAIN)
      http:
        paths:
          - backend:
              service:
                name: api
                port:
                  number: 5585
            path: /(.*)
            pathType: ImplementationSpecific