apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: file-manager
  namespace: 5stack
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "4G"
    nginx.ingress.kubernetes.io/client-max-body-size: "4G"
spec:
  ingressClassName: nginx
  rules:
    - host: $(API_DOMAIN)
      http:
        paths:
          - backend:
              service:
                name: api
                port:
                  number: 5585
            path: /file-manager
            pathType: Prefix