apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: typesense
  namespace: 5stack
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`$(TYPESENSE_HOST)`)
      kind: Rule
      services:
        - name: typesense
          port: 8108
  tls:
    secretName: 5stack-ssl