apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: hasura
  namespace: 5stack
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`$(API_DOMAIN)`) && Path(`/v2/healthz`)
      kind: Rule
      services:
        - name: hasura
          port: 8080
      middlewares:
        - name: rewrite-healthz
  tls:
    secretName: 5stack-ssl
