apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: queues
  namespace: 5stack
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`queues.5stack.localhost`)
      kind: Rule
      services:
        - name: api
          port: 5585
      middlewares:
        - name: rewrite-queues
  tls:
    secretName: 5stack-ssl