apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: hasura-dashboard
  namespace: 5stack
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`hasura.5stack.localhost`)
      kind: Rule
      services:
        - name: hasura
          port: 8080
  tls:
    secretName: 5stack-ssl